name: Release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write #  태그 푸시 권한 부여

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Git user
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Read package.json version
              id: pkg
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Create Git Tag
              run: |
                  git tag v${VERSION}
                  git push origin v${VERSION}

            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ env.VERSION }}
                  release_name: Release v${{ env.VERSION }}
                  draft: false
                  prerelease: false
